#ifndef GUARD_tilesets_H
#define GUARD_tilesets_H

extern const u32 gTilesetTiles_General[];
extern const u16 gTilesetPalettes_General[][16];

extern const struct Tileset *const gTilesetPointer_SecretBase;
extern const struct Tileset *const gTilesetPointer_SecretBaseRedCave;

extern const struct Tileset gTileset_Building;
extern const struct Tileset gTileset_BuildingFrlg;
extern const struct Tileset gTileset_BrendansMaysHouse;
extern const struct Tileset gTileset_GenericBuilding1;
extern const struct Tileset gTileset_GenericBuilding2;
extern const struct Tileset gTileset_General;
extern const struct Tileset gTileset_Petalburg;
extern const struct Tileset gTileset_Rustboro;
extern const struct Tileset gTileset_Fallarbor;
extern const struct Tileset gTileset_Mauville;
extern const struct Tileset gTileset_Slateport;
extern const struct Tileset gTileset_Dewford;
extern const struct Tileset gTileset_Lilycove;
extern const struct Tileset gTileset_Mossdeep;
extern const struct Tileset gTileset_Sootopolis;
extern const struct Tileset gTileset_EverGrande;
extern const struct Tileset gTileset_Pacifidlog;
extern const struct Tileset gTileset_PetalburgGym;
extern const struct Tileset gTileset_PokemonCenter;
extern const struct Tileset gTileset_InsideShip;
extern const struct Tileset gTileset_Fallarbor;
extern const struct Tileset gTileset_Shop;
extern const struct Tileset gTileset_Dewford;
extern const struct Tileset gTileset_BattleFrontier;
extern const struct Tileset gTileset_BattleFrontierOutsideWest;
extern const struct Tileset gTileset_BattleFrontierOutsideEast;
extern const struct Tileset gTileset_BattleArena;
extern const struct Tileset gTileset_BattleDome;
extern const struct Tileset gTileset_BattlePalace;
extern const struct Tileset gTileset_Slateport;
extern const struct Tileset gTileset_Mauville;
extern const struct Tileset gTileset_BattleFrontierOutsideWest;
extern const struct Tileset gTileset_BattleTent;
extern const struct Tileset gTileset_TrainerHill;
extern const struct Tileset gTileset_General_Frlg;
extern const struct Tileset gTileset_Lab_Frlg;
extern const struct Tileset gTileset_PalletTown;
extern const struct Tileset gTileset_ViridianCity;
extern const struct Tileset gTileset_PewterCity;
extern const struct Tileset gTileset_SaffronCity;
extern const struct Tileset gTileset_CeruleanCity;
extern const struct Tileset gTileset_LavenderTown;
extern const struct Tileset gTileset_VermilionCity;
extern const struct Tileset gTileset_CeladonCity;
extern const struct Tileset gTileset_FuchsiaCity;
extern const struct Tileset gTileset_CinnabarIsland;
extern const struct Tileset gTileset_SeviiIslands123;
extern const struct Tileset gTileset_SeviiIslands45;
extern const struct Tileset gTileset_SeviiIslands67;
extern const struct Tileset gTileset_DepartmentStore;
extern const struct Tileset gTileset_PokemonCenterFrlg;
extern const struct Tileset gTileset_SilphCo;
extern const struct Tileset gTileset_SSAnne;
extern const struct Tileset gTileset_SeaCottage;
extern const struct Tileset gTileset_TrainerTower;

extern const struct Tileset gTileset_BerryForest;
extern const struct Tileset gTileset_BikeShop_Frlg;
extern const struct Tileset gTileset_BurgledHouse;
extern const struct Tileset gTileset_CableClub_Frlg;
extern const struct Tileset gTileset_Cave_Frlg;
extern const struct Tileset gTileset_CeladonGym;
extern const struct Tileset gTileset_CeruleanCave;
extern const struct Tileset gTileset_CeruleanGym;
extern const struct Tileset gTileset_CinnabarGym;
extern const struct Tileset gTileset_Condominiums;
extern const struct Tileset gTileset_DiglettsCave;
extern const struct Tileset gTileset_FanClubDaycare;
extern const struct Tileset gTileset_FuchsiaGym;
extern const struct Tileset gTileset_GameCorner;
extern const struct Tileset gTileset_HallOfFame;
extern const struct Tileset gTileset_HoennBuilding;
extern const struct Tileset gTileset_IndigoPlateau;
extern const struct Tileset gTileset_IslandHarbor_Frlg;
extern const struct Tileset gTileset_Mart;
extern const struct Tileset gTileset_MtEmber;
extern const struct Tileset gTileset_Museum;
extern const struct Tileset gTileset_NavelRock_Frlg;
extern const struct Tileset gTileset_PewterGym;
extern const struct Tileset gTileset_PokemonLeague;
extern const struct Tileset gTileset_PokemonMansion;
extern const struct Tileset gTileset_PokemonTower;
extern const struct Tileset gTileset_PowerPlant;
extern const struct Tileset gTileset_RestaurantHotel;
extern const struct Tileset gTileset_RockTunnel;
extern const struct Tileset gTileset_SafariZoneBuilding;
extern const struct Tileset gTileset_SaffronGym;
extern const struct Tileset gTileset_School;
extern const struct Tileset gTileset_SeafoamIslands;
extern const struct Tileset gTileset_TanobyRuins;
extern const struct Tileset gTileset_UndergroundPath;
extern const struct Tileset gTileset_VermilionGym;
extern const struct Tileset gTileset_ViridianForest;
extern const struct Tileset gTileset_ViridianGym;

#endif //GUARD_tilesets_H
